export const PONDICHERRY_AREAS = [
    "White Town",
    "French Quarter",
    "Heritage Town",
    "Goubert Avenue",
    "Beach Road",
    "Mission Street",
    "MG Road",
    "Lawspet",
    "Muthialpet",
    "Mudaliarpet",
    "Reddiarpalayam",
    "Thattanchavady",
    "Oulgaret",
    "Kamaraj Nagar",
    "Ellaipillaichavady",
    "Indira Nagar",
    "Anna Nagar",
    "Brindavanam",
    "Rainbow Nagar",
    "Natesan Nagar",
    "Krishna Nagar",
    "Jeevanandam Nagar",
    "Villianur",
    "Ariyankuppam",
    "Bahour",
    "Kalapet",
    "Pillaichavady",
    "Kombakkam",
    "Karuvadikuppam",
    "Kottakuppam",
    "Gorimedu",
    "Kurumbapet",
    "Nettapakkam",
    "Thirubuvanai",
    "Sedarapet",
    "Manavely",
    "Nonankuppam",
    "Moolakulam",
    "Vazhudavur Road",
    "Cuddalore Road",
    "ECR",
    "Dindivanam Road"
];
